export enum STRATEGY_LABEL {
  ENGLISH = "ENGLISH",
  LEARN_TECHNICAL = "LEARN_TECHNICAL",
  BADMINTON = "BADMINTON",
}

export enum STRATEGY_STATUS {
  NOT_STARTED = "NOT_STARTED",
  IN_PROCESS = "IN_PROCESS",
  COMPLETED = "COMPLETED",
  DELAY = "DELAY",
}
